// Define the types for the external user and item
export interface ExternalUser {
  id: string,
  name: string,
  user_type?: string | null,
}

export interface ExternalItem {
  account: ExternalAccount | null,
  brand: string | null,
  category: {
    id: string,
    name: string,
  } | null,
  color: string | null,
  cost_per: number | null,
  created: string,
  created_by: ExternalUser,
  custom_fields?: unknown[],
  custom_fields_map?: unknown,
  days_on_shelf?: number,
  deleted: string | null,
  description: string | null,
  details: string | null,
  expires?: string | null,
  id: string,
  inventory_type: string,
  last_sold?: string | null,
  last_viewed?: string | null,
  printed?: string | null,
  quantity?: number | null,
  shelf: string | null,
  schedule_start?: string | null,
  shopify_product_id: string | null,
  size: string | null,
  sku: string,
  split: number | null,
  split_price: number | null,
  status: ExternalItemStatus,
  tag_price: number | null,
  tax_exempt?: boolean,
  terms: string | null,
  title: string | null,
}



export interface ExternalItemStatus {
  active?: number,
  damaged?: number,
  donated?: number,
  lost?: number,
  parked?: number,
  returned_to_owner?: number,
  sold?: number,
  sold_on_legacy?: number,
  sold_on_shopify?: number,
  sold_on_square?: number,
  sold_on_third_party?: number,
  stolen?: number,
  to_be_returned?: number,
}


export interface ExternalAccount {
  address_line_1?: string | null, // "123 Main St.",
  address_line_2?: string | null, // "Suite 100",
  balance?: number | null, // 7700,
  city?: string | null, // "San Francisco",
  company?: string | null, // "Acme Inc.",
  created?: string | null, // "2019-08-24T14:15:22Z",
  created_by?: ExternalUser | null, // "4c1f9fb6-5717-4df3-9786-e96deaab9ed8",
  custom_fields: unknown[],
  default_inventory_type?: string | null, // "consignment",
  default_split?: number | null, // 0.5,
  default_terms?: string | null, // "return_to_consignor",
  deleted?: string | null, // null,
  email?: string | null, // "john.doe@gmail.com",
  email_notifications_enabled?: boolean | null, // true,
  first_name?: string | null, // "John",
  id: string, // "4c1f9fb6-5717-4df3-9786-e96deaab9ed8",
  last_activity?: string | null, // "2019-08-24T14:15:22Z",
  last_item_entered?: string | null, // null,
  last_name?: string | null, // "Doe",
  last_settlement?: string | null, // null,
  number: string, // "000031",
  number_of_items?: number | null, // 5,
  number_of_purchases?: number | null, // 3,
  phone_number?: string | null, // "555-555-5555",
  postal_code?: string | null, // "94103",
  state?: string | null, // "CA",
  tags?: string[] | null, // "VIP",
  unpaid_balance_from?: string | null, // 7700
}

export interface ExternalItemSale {
  channel: string,
  id: string,
  price_per: number,
  quantity: number,
  sold_at: string,
}

export interface ExternalSale {
  amounts_tendered?: {
    card: number,
    cash: number,
    check: number,
    gift_card: number,
    manual: number,
    store_credit: number,
  },
  cashier?: ExternalUser | null,
  change: number | null,
  cogs?: number | null,
  consignor_portion?: number | null,
  created: string,
  customer?: ExternalAccount | null,
  discounts?: string[] | null,
  finalized?: string | null,
  id: string,
  memo?: string | null,
  number?: string | null,
  parked?: string | null,
  receipt_url?: string | null,
  refunded_amount?: number | null,
  status?: string,
  store_portion?: number | null,
  subtotal?: number | null,
  taxes?: string[] | null,
  total?: number | null,
  total_tendered?: number | null,
  voided?: string | null
}
